// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ijpfzzgwyngixazfmdpd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqcGZ6emd3eW5naXhhemZtZHBkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NjExODIsImV4cCI6MjA2MDEzNzE4Mn0.G-JRredOMJgBaiWtjbHoVbv6Iy4cnPtW9SDugbzgDGY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);